import type { Metadata } from "next";
import "./globals.css";
import { montserrat, inter, actOfRejection } from "@/lib/fonts";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";

export const metadata: Metadata = {
	title: "vtmerch.com",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${montserrat.variable} ${inter.variable} ${actOfRejection.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
			</body>
		</html>
	);
}
